name: "adhoc_test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    # - uses: DeterminateSystems/magic-nix-cache-action@main
    # Don't waste cache access in this adhoc test
    - run: nix-shell -p nix-info --run "nix-info -m"
    - run: nix-shell -p neovim
    - run: |
       nix-shell -p ripgrep
       nix-shell -p eza
    - name: FileZilla
      run: |
           if [ "$RUNNER_OS" == "Linux" ]; then
              nix-shell -p filezilla
           elif [ "$RUNNER_OS" == "macOS" ]; then
                echo "SKIP $RUNNER_OS not supported"
           else
                echo "$RUNNER_OS not supported"
                exit 1
           fi
    - name: LibreOffice
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
              nix-shell -p libreoffice
         elif [ "$RUNNER_OS" == "macOS" ]; then
              nix-shell -p libreoffice-bin
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi
    - name: Beancount
      run: |
        nix-shell -p fava beancount
        # pandas
    - run: nix-shell -p geany
    - run: nix-shell -p sioyek
