name: "lix_darwin_manual"
env:
  CURRENT_STABLE_CHANNEL: nixpkgs-24.05-darwin
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest,  macos-14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix-shell -p nix-info --run "nix-info -m"
    - name: Install nix darwin
      run: |
        nix run nix-darwin -- switch --flake  $(pwd)
    - run: nix-shell -p nix-info --run "nix-info -m"
    # In future use https://git.lix.systems/lix-project/lix-install-action
        
