name: "adhoc_test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix-shell -p nix-info --run "nix-info -m"
    - run: nix-shell .github/workflows/loop.sh
