name: "nix_darwin"
env:
  CURRENT_STABLE_CHANNEL: nixpkgs-23.05-darwin
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix-shell -p nix-info --run "nix-info -m"
    - run: |
        export NIX_PATH=darwin-config=$HOME/.nixpkgs/darwin-configuration.nix:$HOME/.nix-defexpr/channels:$NIX_PATH
        echo $NIX_PATH
    - run: |
        mkdir ~/.nixpkgs
        cp darwin-configuration.nix ~/.nixpkgs/darwin-configuration.nix
    - run: |
        nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
        ./result/bin/darwin-installer

