name: "nix_darwin"
env:
  CURRENT_STABLE_CHANNEL: nixpkgs-23.05-darwin
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix-shell -p nix-info --run "nix-info -m"
    - run: |
         nix-env --switch-profile darwin-configuration.nix 
    - run: nix-env -iA nixpkgs.ripgrep
